export const BUTTON_CLICKED = 'BUTTON_CLICKED';
export const LETTER_GUESSED = 'LETTER_GUESSED';
export const SET_GAME_WORD_ANSWER = 'SET_GAME_WORD_ANSWER';
export const USER_WON = 'USER_WON';
export const DECREMENT_GUESSES = 'DECREMENT_GUESSES';
export const SET_NUMBER_OF_GUESSES = 'SET_NUMBER_OF_GUESSES'